@include('partials.head')
<body>
    @include('partials.navigation')
    <main>
        @yield('content-main')
    </main>
    <footer>
        @include('partials.footer')
    </footer>
    @include('partials.flash-messages')
</body>
</html>
